# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finviz', '0002_auto_20180804_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='market',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
